<a href="https://colab.research.google.com/github/ManishKumar771/file_data/blob/main/pandas_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np
arr = np.array([10,15,20,19,30])
arr_f = arr[(arr > 10) & (arr < 20)]
print(arr_f)

[15 19]


In [ ]:

arr = np.array([10,15,20,19,30])
arr_f = arr[for i in range(10)]
print(arr_f)

[15 19]


In [ ]:
arr = np.array([5, 6, 7, 8, 11, 24, 16, 19, 25])
arr_w = np.where((arr > 10) & (arr < 20), arr * 2, arr + 2)
print(arr_w)

[ 7  8  9 10 22 26 32 38 27]


In [ ]:
arr = np.array([15, 20, 5, 6,12, 18, 9])

arr_f = np.where((arr > 10) & (arr < 20), arr * 2, arr + 10)

print(arr_f)

[30 30 15 16 24 36 19]


In [ ]:


arr=np.array([[1,2,3],[4,5,6]])

arr1=np.array([[7,8,9],[10,11,12]])

result =np.vstack((arr,arr1))

print(result)






[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

arr1=np.array([[7,8,9],[10,11,12]])

result =np.hstack((arr,arr1))

print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
import numpy as np

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print(sales_data)
print(sales_data.shape)
print("Dimensions:", sales_data.ndim)
print("Total Elements:", sales_data.size)
print("restaurant_id: ", sales_data[:, 0])
print("2021 sales: ", sales_data[:, 1])
print("2024 sales: ", sales_data[:, 4])
print(np.max(sales_data[:, 1:]))
print(np.min(sales_data[:, 1:]))
print("\nTotal 2021 Sales:", np.sum(sales_data[:, 1]))
print("Average 2024 Sales:", np.mean(sales_data[:, 4]))
print(np.sum(sales_data[:, 1:], axis=1))
print(np.mean(sales_data[:, 1:], axis=1))

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
(5, 5)
Dimensions: 2
Total Elements: 25
restaurant_id:  [1 2 3 4 5]
2021 sales:  [150000 120000 200000 180000 160000]
2024 sales:  [250000 190000 300000 270000 230000]
300000
120000

Total 2021 Sales: 810000
Average 2024 Sales: 248000.0
[800000 610000 990000 900000 780000]
[200000. 152500. 247500. 225000. 195000.]


In [23]:

import pandas as pd
import io
import requests

print("-----csv-----")

url = "https://raw.githubusercontent.com/ManishKumar771/file_data/main/file.csv"

df = pd.read_csv(url)
print(df)


print("\n-----json-----")


url01 = "https://raw.githubusercontent.com/ManishKumar771/file_data/main/data01.json"

ds = pd.read_json(url01)
print(ds)





print("\n-----excel-----")

url02 = "https://raw.githubusercontent.com/ManishKumar771/file_data/main/file01.xlsx"


response = requests.get(url02)
dx = pd.read_excel(io.BytesIO(response.content))
print(dx)




-----csv-----
       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male

-----json-----
       name  age
0    nikhil   10
1  devendra   20
2       raj   30
3     hello   40

-----excel-----
       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male
